/**
 * Property-based tests (fast-check) for `@magistr/jscad-stl-validator`.
 *
 * Every property drives `StlValidator.validate()` directly (the pure domain
 * seam) over byte buffers built either fully at random or via
 * `fixtures/stl_builders.ts`. Honors `FC_NUM_RUNS` (verified locally at
 * FC_NUM_RUNS=5000 with no flakes before landing).
 *
 * Invariants:
 *  (a) `validate()` never throws, for ANY byte buffer (fully random bytes,
 *      any length) — the parser must degrade gracefully, never crash.
 *  (b) the result always matches the model's OWN `resources.report.schema`
 *      (well-formed shape).
 *  (c) `valid === (issues.length === 0)` — always, by construction, for any
 *      input (empty / too-small / all-zero / binary / ascii).
 *  (d) for a GUARANTEED-binary buffer (header forced to never read "solid")
 *      of length >= 84 with at least one non-zero byte (so the all-zero
 *      early-return doesn't apply), `triangleCount === floor((len-84)/50)` —
 *      restricted to len>=84 and non-all-zero so the invariant can't ever
 *      be asserted against the two special-cased early-return branches
 *      (too-small returns 0 unconditionally; all-zero also returns 0
 *      unconditionally), which would make it flake/fail spuriously.
 *
 * `jscad_stl_validator.ts` / `jscad/stl_validator.ts` are BYTE-FROZEN. All
 * fixture content is synthetic — see fixtures/PROVENANCE.md.
 */
import { assert } from "jsr:@std/assert@1";
import fc from "npm:fast-check@4.8.0";
import { model } from "./jscad_stl_validator.ts";
import { StlValidator } from "./jscad/stl_validator.ts";

const ENV_RUNS = Deno.env.get("FC_NUM_RUNS");
const NIGHT = (n: number): number => (ENV_RUNS ? Number(ENV_RUNS) : n);
const FC_RUNS = { numRuns: NIGHT(100) };

// ---------------------------------------------------------------------------
// (a) never throws, for any byte buffer
// ---------------------------------------------------------------------------

Deno.test("property: validate() never throws, for any randomly generated byte buffer", () => {
  fc.assert(
    fc.property(
      fc.uint8Array({ minLength: 0, maxLength: 512 }),
      (bytes) => {
        StlValidator.validate(bytes); // throws -> fc.assert fails the test
        return true;
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (b) result always matches the model's own report schema
// ---------------------------------------------------------------------------

Deno.test("property: validate()'s result always matches model.resources.report.schema, for any randomly generated byte buffer", () => {
  fc.assert(
    fc.property(
      fc.uint8Array({ minLength: 0, maxLength: 512 }),
      (bytes) => {
        const report = StlValidator.validate(bytes);
        model.resources.report.schema.parse(report);
        return true;
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (c) valid === (issues.length === 0), universally
// ---------------------------------------------------------------------------

Deno.test("property: report.valid === (report.issues.length === 0), for any randomly generated byte buffer", () => {
  fc.assert(
    fc.property(
      fc.uint8Array({ minLength: 0, maxLength: 512 }),
      (bytes) => {
        const report = StlValidator.validate(bytes);
        return report.valid === (report.issues.length === 0);
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (d) triangleCount === floor((len-84)/50) for guaranteed-binary, non-empty,
//     non-all-zero, len>=84 buffers.
// ---------------------------------------------------------------------------

// A buffer built entirely by this generator: byte[0] is fixed to 0x00 (never
// "s", so `looksAscii` is always false — the buffer takes the binary path
// unconditionally, with no header/reclassification ambiguity) and byte[1] is
// fixed to 0x01 (guarantees at least one non-zero byte, so the all-zero
// early-return branch — which unconditionally reports triangleCount 0
// regardless of length — can never apply and spuriously break the
// invariant). The remaining bytes, including the offset-80 claimed count,
// are fully arbitrary — the invariant must hold regardless of what the
// header or the claimed count says, since `triangleCount` is computed from
// `bytes.byteLength`, never from them.
const arbGuaranteedBinary = fc
  .integer({ min: 0, max: 8 }) // triangle count -> length 84..484
  .chain((n) => {
    const len = 84 + n * 50;
    return fc.uint8Array({ minLength: len, maxLength: len }).map((rest) => {
      const bytes = new Uint8Array(rest);
      bytes[0] = 0x00;
      bytes[1] = 0x01;
      return bytes;
    });
  });

Deno.test("property: triangleCount === floor((byteLength-84)/50) for any guaranteed-binary, non-all-zero buffer of length >= 84", () => {
  fc.assert(
    fc.property(arbGuaranteedBinary, (bytes) => {
      const report = StlValidator.validate(bytes);
      assert(
        report.format === "binary",
        `expected binary, got ${report.format}`,
      );
      const expected = Math.floor((bytes.byteLength - 84) / 50);
      return report.triangleCount === expected;
    }),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// Sanity: the property harness's guaranteed-binary generator actually
// produces buffers the validator classifies as binary (not vacuously true).
// ---------------------------------------------------------------------------

Deno.test("sanity: arbGuaranteedBinary example is classified as binary and matches the schema", () => {
  const bytes = new Uint8Array(184); // 84 + 2*50
  bytes[1] = 1;
  const report = StlValidator.validate(bytes);
  assert(report.format === "binary");
  model.resources.report.schema.parse(report);
});
