/**
 * Property-based tests (fast-check) for @magistr/fidonet-msgbase.
 *
 * Every property drives `model.methods.<m>.execute()` against a synthetic
 * fixture tree built by `fixtures/builders.ts` (real `Deno.readFile`/`readDir`
 * over generated byte-accurate bytes — no FS stubbing) and checks an
 * invariant the shipped code is expected to hold for EVERY generated input,
 * not just the examples the other suites happened to think of.
 *
 * Honors `FC_NUM_RUNS` for the nightly soak (`deno task test:soak`).
 *
 * Invariants:
 *  (a) every emitted message's `format` is one of {jam,squish,fts-0001}, and
 *      the written resource's `count` always equals `messages.length` —
 *      checked against the model's OWN `model.resources.messages.schema`.
 *  (b) search results are always sorted ascending by `timestamp`, for any
 *      generated set of per-message dates.
 *  (c) a search never returns more than `limit` results, for any N/limit.
 *  (d) `readArea`'s offset+limit slice always equals a manual
 *      `Array.prototype.slice` of the full message list.
 *  (e) an arbitrary printable-ASCII from/to/subject round-trips BYTE-EXACT
 *      through the JAM subfield encode -> decodeText(UTF-8) path.
 *  (f) resource-instance-name slug collision is FIXED (bug #7): two
 *      different sender strings that collapse to the same base slug (any
 *      non-alnum separator maps to `_`) now produce DIFFERENT written
 *      instance names, thanks to a trailing hash of the raw query — while
 *      the SAME raw query always produces the IDENTICAL name (determinism).
 *
 * `fidonet_msgbase.ts` received a real-fix pass for 9 latent bugs (see the
 * LOCAL `fidonet-msgbase-latent-bugs` issue-lifecycle model). All fixture
 * content is synthetic — see fixtures/PROVENANCE.md.
 */
import { assert } from "jsr:@std/assert@1";
import fc from "npm:fast-check@4.8.0";
import { model } from "./fidonet_msgbase.ts";
import { buildJamAreaFiles, withTempMsgbase } from "./fixtures/builders.ts";

const ENV_RUNS = Deno.env.get("FC_NUM_RUNS");
const NIGHT = (n: number): number => (ENV_RUNS ? Number(ENV_RUNS) : n);
const FC_RUNS = { numRuns: NIGHT(100) };

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

type Written = { spec: string; name: string; payload: Record<string, unknown> };

function makeCtx(basePath: string) {
  const written: Written[] = [];
  return {
    written,
    ctx: {
      globalArgs: { basePath },
      writeResource: (spec: string, name: string, payload: unknown) => {
        written.push({
          spec,
          name,
          payload: payload as Record<string, unknown>,
        });
        return Promise.resolve({ spec, name });
      },
      readResource: () => Promise.resolve(undefined),
    },
  };
}

type MethodMap = Record<string, {
  arguments: { parse: (a: unknown) => unknown };
  execute: (a: unknown, c: unknown) => Promise<unknown>;
}>;

function run(name: string, args: Record<string, unknown>, ctx: unknown) {
  const method = (model.methods as MethodMap)[name];
  return method.execute(method.arguments.parse(args), ctx);
}

// Printable ASCII, safe to round-trip through UTF-8 (every byte < 0x80).
const arbSafeAscii = fc
  .stringMatching(/^[ -~]{1,24}$/)
  .filter((s) => /[a-zA-Z0-9]/.test(s));

const arbTimestamp = fc.integer({ min: 900000000, max: 1900000000 });

// ---------------------------------------------------------------------------
// (a) format + count invariant, schema-valid, over a generated area
// ---------------------------------------------------------------------------

Deno.test("property: every readArea message has format 'jam' and count === messages.length, for any generated set of JAM messages", async () => {
  await fc.assert(
    fc.asyncProperty(
      fc.array(
        fc.record({
          from: arbSafeAscii,
          subject: arbSafeAscii,
          ts: arbTimestamp,
        }),
        { minLength: 0, maxLength: 8 },
      ),
      async (specs) => {
        const { jhr, jdt } = buildJamAreaFiles({
          messages: specs.map((s, i) => ({
            msgNum: i + 1,
            dateWritten: s.ts,
            from: s.from,
            to: "All",
            subject: s.subject,
          })),
        });
        await withTempMsgbase(
          { areas: { "fido.gen": { kind: "jam", jhr, jdt } } },
          async (basePath) => {
            const { ctx, written } = makeCtx(basePath);
            await run("readArea", { area: "fido.gen", limit: 1000 }, ctx);
            const payload = written[0].payload;
            model.resources.messages.schema.parse(payload);
            const messages = payload.messages as Array<Record<string, unknown>>;
            if (messages.length !== specs.length) return false;
            if (payload.count !== specs.length) return false;
            return messages.every((m) => m.format === "jam");
          },
        );
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (b) search results always sorted ascending by timestamp
// ---------------------------------------------------------------------------

Deno.test("property: searchBySender's results are always sorted ascending by timestamp, regardless of the messages' on-disk order", async () => {
  await fc.assert(
    fc.asyncProperty(
      fc.array(arbTimestamp, { minLength: 1, maxLength: 10 }),
      async (timestamps) => {
        const { jhr, jdt } = buildJamAreaFiles({
          messages: timestamps.map((ts, i) => ({
            msgNum: i + 1,
            dateWritten: ts,
            from: "Property Sender",
            to: "All",
            subject: `msg ${i}`,
          })),
        });
        return await withTempMsgbase(
          { areas: { "fido.sorted": { kind: "jam", jhr, jdt } } },
          async (basePath) => {
            const { ctx, written } = makeCtx(basePath);
            await run(
              "searchBySender",
              { sender: "Property Sender", limit: 1000 },
              ctx,
            );
            const messages = written[0].payload.messages as Array<
              Record<string, unknown>
            >;
            for (let i = 1; i < messages.length; i++) {
              if (
                (messages[i - 1].timestamp as number) >
                  (messages[i].timestamp as number)
              ) {
                return false;
              }
            }
            return messages.length === timestamps.length;
          },
        );
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (c) limit is never exceeded
// ---------------------------------------------------------------------------

Deno.test("property: searchBySender never returns more than `limit` results, for any generated message count and limit", async () => {
  await fc.assert(
    fc.asyncProperty(
      fc.integer({ min: 0, max: 12 }),
      fc.integer({ min: 0, max: 12 }),
      async (n, limit) => {
        const { jhr, jdt } = buildJamAreaFiles({
          messages: Array.from({ length: n }, (_, i) => ({
            msgNum: i + 1,
            dateWritten: 1000000000 + i,
            from: "Limit Test Sender",
            to: "All",
            subject: `msg ${i}`,
          })),
        });
        return await withTempMsgbase(
          { areas: { "fido.limit": { kind: "jam", jhr, jdt } } },
          async (basePath) => {
            const { ctx, written } = makeCtx(basePath);
            await run(
              "searchBySender",
              { sender: "Limit Test Sender", limit },
              ctx,
            );
            const messages = written[0].payload.messages as Array<
              Record<string, unknown>
            >;
            return messages.length <= limit && messages.length <= n;
          },
        );
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (d) offset+limit slice equals a manual Array.prototype.slice
// ---------------------------------------------------------------------------

Deno.test("property: readArea's offset+limit slice always equals Array.prototype.slice(offset, offset+limit) of the full ordered message list", async () => {
  await fc.assert(
    fc.asyncProperty(
      fc.integer({ min: 1, max: 15 }),
      fc.integer({ min: 0, max: 17 }),
      fc.integer({ min: 0, max: 17 }),
      async (n, offset, limit) => {
        const { jhr, jdt } = buildJamAreaFiles({
          messages: Array.from({ length: n }, (_, i) => ({
            msgNum: i + 1,
            dateWritten: 1000000000 + i,
            from: "Slice Sender",
            to: "All",
            subject: `msg ${i}`,
          })),
        });
        return await withTempMsgbase(
          { areas: { "fido.sliceprop": { kind: "jam", jhr, jdt } } },
          async (basePath) => {
            const { ctx, written } = makeCtx(basePath);
            await run(
              "readArea",
              { area: "fido.sliceprop", offset, limit },
              ctx,
            );
            const messages = written[0].payload.messages as Array<
              Record<string, unknown>
            >;
            const expectedNums = Array.from({ length: n }, (_, i) => i + 1)
              .slice(offset, offset + limit);
            const actualNums = messages.map((m) => m.msgNum);
            return JSON.stringify(actualNums) === JSON.stringify(expectedNums);
          },
        );
      },
    ),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (e) ASCII round-trip through the JAM subfield encode/decode path
// ---------------------------------------------------------------------------

Deno.test("property: any printable-ASCII from/subject round-trips byte-exact through readArea", async () => {
  await fc.assert(
    fc.asyncProperty(arbSafeAscii, arbSafeAscii, async (from, subject) => {
      const { jhr, jdt } = buildJamAreaFiles({
        messages: [{
          msgNum: 1,
          dateWritten: 1000000000,
          from,
          to: "All",
          subject,
        }],
      });
      return await withTempMsgbase(
        { areas: { "fido.roundtrip": { kind: "jam", jhr, jdt } } },
        async (basePath) => {
          const { ctx, written } = makeCtx(basePath);
          await run("readArea", { area: "fido.roundtrip" }, ctx);
          const messages = written[0].payload.messages as Array<
            Record<string, unknown>
          >;
          return messages[0].from === from && messages[0].subject === subject;
        },
      );
    }),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// (f) resource-instance-name slug collision FIX + determinism (bug #7)
// ---------------------------------------------------------------------------

const arbAlnum = fc.stringMatching(/^[a-zA-Z0-9]{1,10}$/);
// Any two DIFFERENT non-alphanumeric separators — both collapse to "_" under
// searchBySender's `sender.replace(/[^a-zA-Z0-9]/g, "_")` slugification.
const arbSeparatorPair = fc
  .tuple(
    fc.constantFrom(".", "_", "-", "/", ":", " ", "@"),
    fc.constantFrom(".", "_", "-", "/", ":", " ", "@"),
  )
  .filter(([a, b]) => a !== b);

Deno.test("FIXED (was pin): two different sender strings that collapse to the same base slug now get DIFFERENT resource instance names (bug #7 fix — raw-query hash suffix)", async () => {
  await fc.assert(
    fc.asyncProperty(
      arbAlnum,
      arbAlnum,
      arbSeparatorPair,
      async (base, suffix, [sep1, sep2]) => {
        const sender1 = `${base}${sep1}${suffix}`;
        const sender2 = `${base}${sep2}${suffix}`;
        await withTempMsgbase({}, async (basePath) => {
          const { ctx: ctx1, written: w1 } = makeCtx(basePath);
          await run("searchBySender", { sender: sender1 }, ctx1);
          const { ctx: ctx2, written: w2 } = makeCtx(basePath);
          await run("searchBySender", { sender: sender2 }, ctx2);
          assert(
            w1[0].name !== w2[0].name,
            `expected DIFFERENT resource names for ${
              JSON.stringify(sender1)
            } vs ${
              JSON.stringify(sender2)
            } (same base slug, different raw query) — got identical name ${
              w1[0].name
            }`,
          );
        });
      },
    ),
    FC_RUNS,
  );
});

Deno.test("property: searchBySender's resource instance name is deterministic — the same raw sender string always produces the identical name", async () => {
  await fc.assert(
    fc.asyncProperty(arbAlnum, async (sender) => {
      await withTempMsgbase({}, async (basePath) => {
        const { ctx: ctx1, written: w1 } = makeCtx(basePath);
        await run("searchBySender", { sender }, ctx1);
        const { ctx: ctx2, written: w2 } = makeCtx(basePath);
        await run("searchBySender", { sender }, ctx2);
        assert(
          w1[0].name === w2[0].name,
          `expected deterministic name for ${JSON.stringify(sender)}, got ${
            w1[0].name
          } vs ${w2[0].name}`,
        );
      });
    }),
    FC_RUNS,
  );
});

// ---------------------------------------------------------------------------
// Sanity: the property harness actually builds well-formed areas
// ---------------------------------------------------------------------------

Deno.test("sanity: the JAM area builder used by these properties round-trips a non-trivial example without throwing", async () => {
  const { jhr, jdt } = buildJamAreaFiles({
    messages: [{
      msgNum: 1,
      dateWritten: 1234567890,
      from: "Sanity Sender",
      to: "All",
      subject: "sanity subject",
    }],
  });
  await withTempMsgbase(
    { areas: { "fido.sanity": { kind: "jam", jhr, jdt } } },
    async (basePath) => {
      const { ctx, written } = makeCtx(basePath);
      await run("readArea", { area: "fido.sanity" }, ctx);
      assert(
        (written[0].payload.messages as unknown[]).length === 1,
        "sanity: builder must produce exactly one decodable message",
      );
    },
  );
});
